-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 19:41:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`neuteredspayed_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`neuteredspayed_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`neuteredspayed_info` (
  `Gender` VARCHAR(45) NOT NULL,
  `NeuterSpay` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Gender`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`petowner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`petowner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`petowner` (
  `OwnerID` INT NOT NULL AUTO_INCREMENT,
  `OwnerName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`petrecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`petrecord` ;

CREATE TABLE IF NOT EXISTS `mydb`.`petrecord` (
  `PetID` INT NOT NULL AUTO_INCREMENT,
  `PetName` VARCHAR(45) NOT NULL,
  `Breed` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Markings` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `NeuteredSpayed_Info_Gender` VARCHAR(45) NOT NULL,
  `PetOwner_OwnerName` VARCHAR(45) NOT NULL,
  `petowner_OwnerID` INT NOT NULL,
  PRIMARY KEY (`PetID`, `petowner_OwnerID`),
  CONSTRAINT `fk_PetRecord_NeuteredSpayed_Info1`
    FOREIGN KEY (`NeuteredSpayed_Info_Gender`)
    REFERENCES `mydb`.`neuteredspayed_info` (`Gender`),
  CONSTRAINT `fk_petrecord_petowner1`
    FOREIGN KEY (`petowner_OwnerID`)
    REFERENCES `mydb`.`petowner` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PetRecord_NeuteredSpayed_Info1_idx` ON `mydb`.`petrecord` (`NeuteredSpayed_Info_Gender` ASC);

CREATE INDEX `fk_petrecord_petowner1_idx` ON `mydb`.`petrecord` (`petowner_OwnerID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`trainingschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trainingschedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trainingschedule` (
  `RegistrationID` INT NOT NULL,
  `Trainers` VARCHAR(45) NOT NULL,
  `Classes` VARCHAR(45) NOT NULL,
  `TrainingDate` DATETIME NOT NULL,
  `petrecord_PetID` INT NOT NULL,
  `petrecord_petowner_OwnerID` INT NOT NULL,
  PRIMARY KEY (`RegistrationID`),
  CONSTRAINT `fk_trainingschedule_petrecord1`
    FOREIGN KEY (`petrecord_PetID` , `petrecord_petowner_OwnerID`)
    REFERENCES `mydb`.`petrecord` (`PetID` , `petowner_OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_trainingschedule_petrecord1_idx` ON `mydb`.`trainingschedule` (`petrecord_PetID` ASC, `petrecord_petowner_OwnerID` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classes` (
  `TrainingScheduleID` INT NOT NULL,
  `BasicSkills` VARCHAR(45) NOT NULL,
  `WalkIn` VARCHAR(45) NOT NULL,
  `OffLeash` VARCHAR(45) NOT NULL,
  `AdvancedTricks` VARCHAR(45) NOT NULL,
  `ShowDogs` VARCHAR(45) NOT NULL,
  `PuppyManors` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `trainingschedule_RegistrationID` INT NOT NULL,
  PRIMARY KEY (`TrainingScheduleID`),
  CONSTRAINT `fk_classes_trainingschedule1`
    FOREIGN KEY (`trainingschedule_RegistrationID`)
    REFERENCES `mydb`.`trainingschedule` (`RegistrationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_classes_trainingschedule1_idx` ON `mydb`.`classes` (`trainingschedule_RegistrationID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
